print("Sales Report") 
print("") 
sales_Report = int(input("input the year the sales report is for > £")) 
january_sales = int(input("input January's sales amount > £")) 
february_sales = int(input("input February's sales amount > £")) 
march_sales = int(input("input March's sales amount > £")) 
april_sales = int(input("input April's sales amount > £")) 
may_sales = int(input("input May's sales amount > £")) 
june_sales = int(input("input June's sales amount > £")) 
july_sales = int(input("input July's sales amount > £")) 
august_sales = int(input("input August's sales amount > £")) 
september_sales = int(input("input september's sales amount > £")) 
october_sales = int(input("input october's sales amount > £")) 
november_sales = int(input("input November's sales amount > £")) 
december_sales = int(input("input December's sales amount > £")) 
print("") 
total_sales = (january_sales+february_sales+march_sales+april_sales+may_sales+june_sales+july_sales+august_sales+september_sales+october_sales+november_sales+december_sales) 
print ("The total sales for 2022 are £",total_sales) 
print ("the average monthly sales for 2022 was £", total_sales/12) 
 
